// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/flucurl.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FlucurlBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlucurlBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlucurlBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void flucurl_global_init() {
    return _flucurl_global_init();
  }

  late final _flucurl_global_initPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('flucurl_global_init');
  late final _flucurl_global_init =
      _flucurl_global_initPtr.asFunction<void Function()>();

  void flucurl_global_deinit() {
    return _flucurl_global_deinit();
  }

  late final _flucurl_global_deinitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('flucurl_global_deinit');
  late final _flucurl_global_deinit =
      _flucurl_global_deinitPtr.asFunction<void Function()>();

  void flucurl_upload_append(
    UploadState arg0,
    Field arg1,
  ) {
    return _flucurl_upload_append(
      arg0,
      arg1,
    );
  }

  late final _flucurl_upload_appendPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(UploadState, Field)>>(
          'flucurl_upload_append');
  late final _flucurl_upload_append =
      _flucurl_upload_appendPtr.asFunction<void Function(UploadState, Field)>();

  void flucurl_free_reponse(
    Response arg0,
  ) {
    return _flucurl_free_reponse(
      arg0,
    );
  }

  late final _flucurl_free_reponsePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(Response)>>(
          'flucurl_free_reponse');
  late final _flucurl_free_reponse =
      _flucurl_free_reponsePtr.asFunction<void Function(Response)>();

  void flucurl_free_bodydata(
    ffi.Pointer<BodyData> arg0,
  ) {
    return _flucurl_free_bodydata(
      arg0,
    );
  }

  late final _flucurl_free_bodydataPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<BodyData>)>>(
          'flucurl_free_bodydata');
  late final _flucurl_free_bodydata = _flucurl_free_bodydataPtr
      .asFunction<void Function(ffi.Pointer<BodyData>)>();

  ffi.Pointer<ffi.Void> flucurl_session_init(
    Config config,
  ) {
    return _flucurl_session_init(
      config,
    );
  }

  late final _flucurl_session_initPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(Config)>>(
          'flucurl_session_init');
  late final _flucurl_session_init = _flucurl_session_initPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(Config)>();

  void flucurl_session_terminate(
    ffi.Pointer<ffi.Void> session,
  ) {
    return _flucurl_session_terminate(
      session,
    );
  }

  late final _flucurl_session_terminatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'flucurl_session_terminate');
  late final _flucurl_session_terminate = _flucurl_session_terminatePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<UploadState> flucurl_session_send_request(
    ffi.Pointer<ffi.Void> session,
    Request request,
    ResponseCallback callback,
    DataHandler onData,
    ErrorHandler onError,
  ) {
    return _flucurl_session_send_request(
      session,
      request,
      callback,
      onData,
      onError,
    );
  }

  late final _flucurl_session_send_requestPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<UploadState> Function(
              ffi.Pointer<ffi.Void>,
              Request,
              ResponseCallback,
              DataHandler,
              ErrorHandler)>>('flucurl_session_send_request');
  late final _flucurl_session_send_request =
      _flucurl_session_send_requestPtr.asFunction<
          ffi.Pointer<UploadState> Function(ffi.Pointer<ffi.Void>, Request,
              ResponseCallback, DataHandler, ErrorHandler)>();
}

final class Field extends ffi.Struct {
  external ffi.Pointer<ffi.Char> p;

  @ffi.Int()
  external int len;
}

final class Request extends ffi.Struct {
  external ffi.Pointer<ffi.Char> url;

  external ffi.Pointer<ffi.Char> method;

  @ffi.Int()
  external int content_length;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> headers;

  @ffi.Int()
  external int header_count;

  external ffi.Pointer<ffi.Char> resolved_ip;

  external ffi.Pointer<ffi.Void> mtx;
}

enum HTTPVersion {
  HTTP1_0(0),
  HTTP1_1(1),
  HTTP2(2),
  HTTP3(3);

  final int value;
  const HTTPVersion(this.value);

  static HTTPVersion fromValue(int value) => switch (value) {
        0 => HTTP1_0,
        1 => HTTP1_1,
        2 => HTTP2,
        3 => HTTP3,
        _ => throw ArgumentError("Unknown value for HTTPVersion: $value"),
      };
}

final class Response extends ffi.Struct {
  @ffi.UnsignedInt()
  external int http_version;

  @ffi.Int()
  external int status;

  external ffi.Pointer<Field> headers;

  @ffi.Int()
  external int header_count;

  external ffi.Pointer<ffi.Void> session;
}

final class TLSConfig extends ffi.Struct {
  @ffi.Int()
  external int enable;

  /// Enable certificate verification.
  @ffi.Int()
  external int verify_certificates;

  /// Enable TLS Server Name Indication (SNI).
  @ffi.Int()
  external int enable_sni;

  /// The trusted root certificates in PEM format.
  /// Either specify the root certificate or the full
  /// certificate chain.
  /// The Rust API currently doesn't support trusting a single leaf certificate.
  /// Hint: PEM format starts with `-----BEGIN CERTIFICATE-----`.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> trusted_root_certificates;

  @ffi.Int()
  external int trusted_root_certificates_length;
}

final class Config extends ffi.Struct {
  /// Timeout in seconds.
  @ffi.Int()
  external int timeout;

  /// http or socks5 proxy, in the format of "http://host:port" or
  /// "socks5://host:port". Null for no proxy.
  /// Authentication:
  /// - scheme://user:password@host:port
  external ffi.Pointer<ffi.Char> proxy;

  /// TLS configuration.
  external ffi.Pointer<TLSConfig> tls_config;

  @ffi.UnsignedInt()
  external int http_version;

  @ffi.Int()
  external int keep_alive;

  @ffi.Int()
  external int idle_timeout;

  external ffi
      .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      free_dart_memory;
}

final class BodyData extends ffi.Struct {
  external ffi.Pointer<ffi.Char> data;

  @ffi.Int()
  external int size;

  external ffi.Pointer<ffi.Void> session;
}

final class UploadState extends ffi.Struct {
  external ffi.Pointer<ffi.Void> session;

  external ffi.Pointer<ffi.Void> queue;

  external ffi.Pointer<ffi.Void> curl;

  @ffi.Int()
  external int pause;

  external ffi.Pointer<ffi.Void> mtx;

  @ffi.UnsignedLongLong()
  external int cur;
}

typedef ResponseCallback
    = ffi.Pointer<ffi.NativeFunction<ResponseCallbackFunction>>;
typedef ResponseCallbackFunction = ffi.Void Function(Response);
typedef DartResponseCallbackFunction = void Function(Response);
typedef DataHandler = ffi.Pointer<ffi.NativeFunction<DataHandlerFunction>>;
typedef DataHandlerFunction = ffi.Void Function(ffi.Pointer<BodyData>);
typedef DartDataHandlerFunction = void Function(ffi.Pointer<BodyData>);
typedef ErrorHandler = ffi.Pointer<ffi.NativeFunction<ErrorHandlerFunction>>;
typedef ErrorHandlerFunction = ffi.Void Function(ffi.Pointer<ffi.Char> message);
typedef DartErrorHandlerFunction = void Function(ffi.Pointer<ffi.Char> message);
