// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/flucurl.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FlucurlBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlucurlBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlucurlBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void global_init() {
    return _global_init();
  }

  late final _global_initPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('global_init');
  late final _global_init = _global_initPtr.asFunction<void Function()>();

  void flucurl_free_reponse(
    Response arg0,
  ) {
    return _flucurl_free_reponse(
      arg0,
    );
  }

  late final _flucurl_free_reponsePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(Response)>>(
          'flucurl_free_reponse');
  late final _flucurl_free_reponse =
      _flucurl_free_reponsePtr.asFunction<void Function(Response)>();

  void flucurl_free_bodydata(
    ffi.Pointer<ffi.Char> arg0,
  ) {
    return _flucurl_free_bodydata(
      arg0,
    );
  }

  late final _flucurl_free_bodydataPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'flucurl_free_bodydata');
  late final _flucurl_free_bodydata = _flucurl_free_bodydataPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Void> session_init(
    Config config,
  ) {
    return _session_init(
      config,
    );
  }

  late final _session_initPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(Config)>>(
          'session_init');
  late final _session_init =
      _session_initPtr.asFunction<ffi.Pointer<ffi.Void> Function(Config)>();

  void session_terminate(
    ffi.Pointer<ffi.Void> session,
  ) {
    return _session_terminate(
      session,
    );
  }

  late final _session_terminatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'session_terminate');
  late final _session_terminate =
      _session_terminatePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void session_send_request(
    ffi.Pointer<ffi.Void> session,
    Request request,
    ResponseCallback callback,
    DataHandler onData,
    ErrorHandler onError,
  ) {
    return _session_send_request(
      session,
      request,
      callback,
      onData,
      onError,
    );
  }

  late final _session_send_requestPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>, Request, ResponseCallback,
              DataHandler, ErrorHandler)>>('session_send_request');
  late final _session_send_request = _session_send_requestPtr.asFunction<
      void Function(ffi.Pointer<ffi.Void>, Request, ResponseCallback,
          DataHandler, ErrorHandler)>();
}

final class Field extends ffi.Struct {
  external ffi.Pointer<ffi.Char> key;

  external ffi.Pointer<ffi.Char> value;
}

final class Request extends ffi.Struct {
  external ffi.Pointer<ffi.Char> url;

  external ffi.Pointer<ffi.Char> method;

  external ffi.Pointer<ffi.Char> data;

  @ffi.Int()
  external int content_length;

  external ffi.Pointer<Field> headers;

  @ffi.Int()
  external int header_count;
}

enum HTTPVersion {
  HTTP1_0(0),
  HTTP1_1(1),
  HTTP2(2),
  HTTP3(3);

  final int value;
  const HTTPVersion(this.value);

  static HTTPVersion fromValue(int value) => switch (value) {
        0 => HTTP1_0,
        1 => HTTP1_1,
        2 => HTTP2,
        3 => HTTP3,
        _ => throw ArgumentError("Unknown value for HTTPVersion: $value"),
      };
}

final class Response extends ffi.Struct {
  @ffi.UnsignedInt()
  external int http_version;

  @ffi.Int()
  external int status;

  external ffi.Pointer<Field> headers;

  @ffi.Int()
  external int header_count;
}

final class TLSConfig extends ffi.Struct {
  /// Enable certificate verification.
  @ffi.Int()
  external int verify_certificates;

  /// Enable TLS Server Name Indication (SNI).
  @ffi.Int()
  external int enable_sni;

  /// The trusted root certificates in PEM format.
  /// Either specify the root certificate or the full
  /// certificate chain.
  /// The Rust API currently doesn't support trusting a single leaf certificate.
  /// Hint: PEM format starts with `-----BEGIN CERTIFICATE-----`.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> trusted_root_certificates;

  @ffi.Int()
  external int trusted_root_certificates_length;
}

final class Config extends ffi.Struct {
  /// Timeout in seconds.
  @ffi.Int()
  external int timeout;

  /// http or socks5 proxy, in the format of "http://host:port" or
  /// "socks5://host:port". Null for no proxy.
  /// Authentication:
  /// - scheme://user:password@host:port
  external ffi.Pointer<ffi.Char> proxy;

  /// DNS resolver function. If null or returns null, the system default
  /// resolver will be used.
  external ffi.Pointer<DNSResolver> dns_resolver;

  /// TLS configuration.
  external ffi.Pointer<TLSConfig> tls_config;

  @ffi.UnsignedInt()
  external int http_version;

  @ffi.Int()
  external int keep_alive;

  @ffi.Int()
  external int idle_timeout;
}

typedef DNSResolver = ffi.Pointer<ffi.NativeFunction<DNSResolverFunction>>;
typedef DNSResolverFunction = ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char> host);

final class BodyData extends ffi.Struct {
  external ffi.Pointer<ffi.Char> data;

  @ffi.Int()
  external int size;
}

typedef ResponseCallback
    = ffi.Pointer<ffi.NativeFunction<ResponseCallbackFunction>>;
typedef ResponseCallbackFunction = ffi.Void Function(Response);
typedef DartResponseCallbackFunction = void Function(Response);
typedef DataHandler = ffi.Pointer<ffi.NativeFunction<DataHandlerFunction>>;
typedef DataHandlerFunction = ffi.Void Function(BodyData);
typedef DartDataHandlerFunction = void Function(BodyData);
typedef ErrorHandler = ffi.Pointer<ffi.NativeFunction<ErrorHandlerFunction>>;
typedef ErrorHandlerFunction = ffi.Void Function(ffi.Pointer<ffi.Char> message);
typedef DartErrorHandlerFunction = void Function(ffi.Pointer<ffi.Char> message);
